[build]
  # Install deps in ./client and then build there
  command = "npm --prefix client install --include=dev && npm --prefix client run build"
  publish = "client/dist"

# Make SPA routes work (prevents 404 on refresh)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--include=dev"