[build]
  command = "npm install --include=dev && npm run build"
  publish = "dist"

# Single-page app routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--include=dev"