[build]
base = "client"
publish = "dist"
command = "npm run build"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
[build]
  base = "client"
  command = "npm run build"
  publish = "dist"

# Fix 404 on client-side routes
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200