[build]
  # Install deps only in the client folder, then build there
  command = "npm --prefix client ci && npm --prefix client run build"
  publish = "client/dist"

# SPA routing so refresh/deep links work
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200